version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test:
    jobs:
      - unit-tests

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: cpu unit tests
          command: "python -m unittest -f cpu"

